// block_behavior 行为包入口：注册方块行为类 GameTest。
// 测试按主角方块的 Cubium 实现分类（src/common/world/block/blocks 的目录结构）拆分到 src/tests/ 子目录，
// 镜像 C++ blocks/ 功能分类（liquid/special/agricultural/building/vegetation 等）。
// 未来为每个方块加行为测试时，放入对应分类目录即可。

// 必须最先 import（副作用执行）：GameTest RegistrationBuilder 跨服务端兼容垫片。
// Cubium 在官方 RegistrationBuilder 之上扩展了 skyAccess 链式方法（基岩 BDS 无此方法，调用抛 TypeError
// 致整个行为包加载失败）。垫片在基岩侧用 prototype 注入把 skyAccess 降级为 no-op，Cubium 侧保留原实现。
// 详见 gametest-shim.ts。
import "./gametest-shim.js";

import { registerLiquidTests } from "./tests/liquid/LiquidTests.js";
import { registerWaterLavaInteractionTests } from "./tests/liquid/WaterLavaInteractionTests.js";
import { registerSpongeTests } from "./tests/special/SpongeTests.js";
import { registerFarmlandTests } from "./tests/agricultural/FarmlandTests.js";
import { registerBoneMealTests } from "./tests/agricultural/BoneMealTests.js";
import { registerCropBoneMealTests } from "./tests/agricultural/CropBoneMealTests.js";
import { registerCropLightThresholdTests } from "./tests/agricultural/CropLightThresholdTests.js";
import { registerCocoaTests } from "./tests/agricultural/CocoaTests.js";
import { registerPumpkinTests } from "./tests/agricultural/PumpkinTests.js";
import { registerHoeTillTests } from "./tests/agricultural/HoeTillTests.js";
import { registerAxeStripTests } from "./tests/building/AxeStripTests.js";
import { registerConcretePowderTests } from "./tests/building/ConcretePowderTests.js";
import { registerFenceConnectionTests } from "./tests/building/FenceConnectionTests.js";
import { registerWallConnectionTests } from "./tests/building/WallConnectionTests.js";
import { registerStairsTests } from "./tests/building/StairsTests.js";
import { registerTrapdoorTests } from "./tests/building/TrapdoorTests.js";
import { registerDoorTests } from "./tests/building/DoorTests.js";
import { registerFenceGateTests } from "./tests/building/FenceGateTests.js";
import { registerFallingBlockTests } from "./tests/falling/FallingBlockTests.js";
import { registerCoralTests } from "./tests/coral/CoralTests.js";
import { registerCactusTests } from "./tests/vegetation/CactusTests.js";
import { registerSugarCaneTests } from "./tests/vegetation/SugarCaneTests.js";
import { registerGrassSpreadTests } from "./tests/vegetation/GrassSpreadTests.js";
import { registerMushroomSpreadTests } from "./tests/vegetation/MushroomSpreadTests.js";
import { registerBambooTests } from "./tests/vegetation/BambooTests.js";
import { registerDoublePlantTests } from "./tests/vegetation/DoublePlantTests.js";
import { registerTallGrassTests } from "./tests/vegetation/TallGrassTests.js";
import { registerLilyPadTests } from "./tests/vegetation/LilyPadTests.js";
import { registerKelpTests } from "./tests/vegetation/KelpTests.js";
import { registerSnowTests } from "./tests/ice/SnowTests.js";
import { registerSnowMeltTests } from "./tests/ice/SnowMeltTests.js";
import { registerIceMeltTests } from "./tests/ice/IceMeltTests.js";
import { registerTntTests } from "./tests/redstone/TntTests.js";
import { registerRedstoneWireTests } from "./tests/redstone/RedstoneWireTests.js";
import { registerRedstoneLampTests } from "./tests/redstone/RedstoneLampTests.js";
import { registerCopperBulbTests } from "./tests/redstone/CopperBulbTests.js";
import { registerHopperTests } from "./tests/redstone/HopperTests.js";
import { registerObserverTests } from "./tests/redstone/ObserverTests.js";
import { registerPressurePlateTests } from "./tests/redstone/PressurePlateTests.js";
import { registerButtonTests } from "./tests/redstone/ButtonTests.js";
import { registerLeverTests } from "./tests/redstone/LeverTests.js";
import { registerDaylightDetectorTests } from "./tests/redstone/DaylightDetectorTests.js";
import { registerRepeaterTests } from "./tests/redstone/RepeaterTests.js";
import { registerComparatorTests } from "./tests/redstone/ComparatorTests.js";
import { registerNoteBlockTests } from "./tests/redstone/NoteBlockTests.js";
import { registerActivatorRailTests } from "./tests/redstone/ActivatorRailTests.js";
import { registerPoweredRailTests } from "./tests/redstone/PoweredRailTests.js";
import { registerRailTests } from "./tests/redstone/RailTests.js";
import { registerTripWireHookTests } from "./tests/redstone/TripWireHookTests.js";
import { registerSculkSensorTests } from "./tests/sculk/SculkSensorTests.js";
import { registerSculkShriekerTests } from "./tests/sculk/SculkShriekerTests.js";
import { registerCampfireTests } from "./tests/decorative/CampfireTests.js";
import { registerFrostWalkerTests } from "./tests/decorative/FrostWalkerTests.js";
import { registerPaneConnectionTests } from "./tests/decorative/PaneConnectionTests.js";
import { registerLanternTests } from "./tests/decorative/LanternTests.js";
import { registerTorchTests } from "./tests/decorative/TorchTests.js";
import { registerLadderTests } from "./tests/decorative/LadderTests.js";
import { registerScaffoldingTests } from "./tests/decorative/ScaffoldingTests.js";
import { registerGlazedTerracottaTests } from "./tests/decorative/GlazedTerracottaTests.js";
import { registerMagmaTests } from "./tests/nether/MagmaTests.js";
import { registerSoulFireTests } from "./tests/nether/SoulFireTests.js";
import { registerFireTests } from "./tests/nether/FireTests.js";
import { registerNetherRootsTests } from "./tests/nether/NetherRootsTests.js";
import { registerCactusFlowerTests } from "./tests/garden/CactusFlowerTests.js";
import { registerWildflowersTests } from "./tests/garden/WildflowersTests.js";
import { registerDryVegetationTests } from "./tests/garden/DryVegetationTests.js";
import { registerLeafLitterTests } from "./tests/garden/LeafLitterTests.js";
import { registerFireflyBushTests } from "./tests/garden/FireflyBushTests.js";
import { registerSlimeBlockTests } from "./tests/special/SlimeBlockTests.js";
import { registerHoneyBlockTests } from "./tests/special/HoneyBlockTests.js";
import { registerHayBlockTests } from "./tests/special/HayBlockTests.js";
import { registerWebTests } from "./tests/special/WebTests.js";
import { registerWitherRoseTests } from "./tests/vegetation/WitherRoseTests.js";
import { registerSweetBerryBushTests } from "./tests/vegetation/SweetBerryBushTests.js";
import { registerLeavesDistanceTests } from "./tests/vegetation/LeavesDistanceTests.js";
import { registerPointedDripstoneTests } from "./tests/cave/PointedDripstoneTests.js";
import { registerPowderSnowWalkableTests } from "./tests/cave/PowderSnowWalkableTests.js";
import { registerPowderSnowFreezeTests } from "./tests/cave/PowderSnowFreezeTests.js";
import { registerCaveVinesTests } from "./tests/cave/CaveVinesTests.js";
import { registerSporeBlossomTests } from "./tests/cave/SporeBlossomTests.js";
import { registerMossTests } from "./tests/cave/MossTests.js";
import { registerAmethystBudGrowthTests } from "./tests/cave/AmethystBudGrowthTests.js";
import { registerVineTests } from "./tests/vegetation/VineTests.js";
import { registerAnvilTests } from "./tests/functional/AnvilTests.js";
import { registerComposterTests } from "./tests/functional/ComposterTests.js";
import { registerCauldronTests } from "./tests/functional/CauldronTests.js";
import { registerLecternTests } from "./tests/functional/LecternTests.js";
import { registerJukeboxTests } from "./tests/functional/JukeboxTests.js";
import { registerDecoratedPotTests } from "./tests/functional/DecoratedPotTests.js";
import { registerFlowerPotTests } from "./tests/decorative/FlowerPotTests.js";
import { registerCandleTests } from "./tests/decorative/CandleTests.js";
import { registerCakeTests } from "./tests/functional/CakeTests.js";
import { registerCandleCakeTests } from "./tests/functional/CandleCakeTests.js";
import { registerRespawnAnchorTests } from "./tests/functional/RespawnAnchorTests.js";
import { registerDragonEggTests } from "./tests/end/DragonEggTests.js";
import { registerEndRodTests } from "./tests/end/EndRodTests.js";
import { registerSeaPickleTests } from "./tests/ocean/SeaPickleTests.js";
import { registerBubbleColumnTests } from "./tests/ocean/BubbleColumnTests.js";
import { registerBeehiveTests } from "./tests/mob/BeehiveTests.js";
import { registerShovelTests } from "./tests/decorative/ShovelTests.js";
import { registerCarpetTests } from "./tests/decorative/CarpetTests.js";
import { registerChainTests } from "./tests/decorative/ChainTests.js";
import { registerCopperGolemStatueTests } from "./tests/copper/CopperGolemStatueTests.js";
import { registerCopperWaxTests } from "./tests/copper/CopperWaxTests.js";
import { registerCopperOxidationTests } from "./tests/copper/CopperOxidationTests.js";
import { registerBedTests } from "./tests/functional/BedTests.js";
import { registerBellTests } from "./tests/functional/BellTests.js";
import { registerBannerTests } from "./tests/decorative/BannerTests.js";
import { registerBigDripleafTests } from "./tests/cave/BigDripleafTests.js";
import { registerBigDripleafStemTests } from "./tests/cave/BigDripleafStemTests.js";
import { registerSmallDripleafTests } from "./tests/cave/SmallDripleafTests.js";
import { registerPaleHangingMossTests } from "./tests/pale_garden/PaleHangingMossTests.js";
import { registerEyeblossomTests } from "./tests/pale_garden/EyeblossomTests.js";
import { registerCreakingHeartTests } from "./tests/pale_garden/CreakingHeartTests.js";
import { registerTurtleEggTests } from "./tests/mob/TurtleEggTests.js";
import { registerBrewingStandTests } from "./tests/functional/BrewingStandTests.js";
import { registerFurnaceTests } from "./tests/functional/FurnaceTests.js";
import { registerBarrelTests } from "./tests/functional/BarrelTests.js";
import { registerGrindstoneTests } from "./tests/functional/GrindstoneTests.js";
import { registerStonecutterTests } from "./tests/functional/StonecutterTests.js";
import { registerLoomTests } from "./tests/functional/LoomTests.js";
import { registerCartographyTableTests } from "./tests/functional/CartographyTableTests.js";
import { registerFletchingTableTests } from "./tests/functional/FletchingTableTests.js";
import { registerSmithingTableTests } from "./tests/functional/SmithingTableTests.js";
import { registerDispenserTests } from "./tests/redstone/DispenserTests.js";
import { registerDropperTests } from "./tests/redstone/DropperTests.js";
import { registerPistonTests } from "./tests/redstone/PistonTests.js";
import { registerStickyPistonTests } from "./tests/redstone/StickyPistonTests.js";
import { registerRedstoneBlockTests } from "./tests/redstone/RedstoneBlockTests.js";
import { registerRedstoneOreTests } from "./tests/redstone/RedstoneOreTests.js";
import { registerRedstoneTorchTests } from "./tests/redstone/RedstoneTorchTests.js";
import { registerTargetBlockTests } from "./tests/redstone/TargetBlockTests.js";
import { registerWeightedPressurePlateTests } from "./tests/redstone/WeightedPressurePlateTests.js";
import { registerBeaconTests } from "./tests/functional/BeaconTests.js";

registerLiquidTests();
registerWaterLavaInteractionTests();
registerSpongeTests();
registerFarmlandTests();
registerBoneMealTests();
registerCropBoneMealTests();
registerCropLightThresholdTests();
registerCocoaTests();
registerPumpkinTests();
registerHoeTillTests();
registerAxeStripTests();
registerConcretePowderTests();
registerFenceConnectionTests();
registerWallConnectionTests();
registerStairsTests();
registerTrapdoorTests();
registerDoorTests();
registerFenceGateTests();
registerFallingBlockTests();
registerCoralTests();
registerCactusTests();
registerSugarCaneTests();
registerGrassSpreadTests();
registerMushroomSpreadTests();
registerBambooTests();
registerDoublePlantTests();
registerTallGrassTests();
registerLilyPadTests();
registerKelpTests();
registerSnowTests();
registerSnowMeltTests();
registerIceMeltTests();
registerTntTests();
registerRedstoneWireTests();
registerRedstoneLampTests();
registerCopperBulbTests();
registerHopperTests();
registerObserverTests();
registerPressurePlateTests();
registerButtonTests();
registerLeverTests();
registerDaylightDetectorTests();
registerRepeaterTests();
registerComparatorTests();
registerNoteBlockTests();
registerActivatorRailTests();
registerPoweredRailTests();
registerRailTests();
registerTripWireHookTests();
registerSculkSensorTests();
registerSculkShriekerTests();
registerCampfireTests();
registerFrostWalkerTests();
registerPaneConnectionTests();
registerLanternTests();
registerTorchTests();
registerLadderTests();
registerScaffoldingTests();
registerGlazedTerracottaTests();
registerMagmaTests();
registerSoulFireTests();
registerFireTests();
registerNetherRootsTests();
registerCactusFlowerTests();
registerWildflowersTests();
registerDryVegetationTests();
registerLeafLitterTests();
registerFireflyBushTests();
registerSlimeBlockTests();
registerHoneyBlockTests();
registerHayBlockTests();
registerWebTests();
registerWitherRoseTests();
registerSweetBerryBushTests();
registerLeavesDistanceTests();
registerPointedDripstoneTests();
registerPowderSnowWalkableTests();
registerPowderSnowFreezeTests();
registerCaveVinesTests();
registerSporeBlossomTests();
registerMossTests();
registerAmethystBudGrowthTests();
registerVineTests();
registerAnvilTests();
registerComposterTests();
registerCauldronTests();
registerLecternTests();
registerJukeboxTests();
registerDecoratedPotTests();
registerFlowerPotTests();
registerCandleTests();
registerCakeTests();
registerCandleCakeTests();
registerRespawnAnchorTests();
registerDragonEggTests();
registerEndRodTests();
registerSeaPickleTests();
registerBubbleColumnTests();
registerBeehiveTests();
registerShovelTests();
registerCarpetTests();
registerChainTests();
registerCopperGolemStatueTests();
registerCopperWaxTests();
registerCopperOxidationTests();
registerBedTests();
registerBellTests();
registerBannerTests();
registerBigDripleafTests();
registerBigDripleafStemTests();
registerSmallDripleafTests();
registerPaleHangingMossTests();
registerEyeblossomTests();
registerCreakingHeartTests();
registerTurtleEggTests();
registerBrewingStandTests();
registerFurnaceTests();
registerBarrelTests();
registerGrindstoneTests();
registerStonecutterTests();
registerLoomTests();
registerCartographyTableTests();
registerFletchingTableTests();
registerSmithingTableTests();
registerDispenserTests();
registerDropperTests();
registerPistonTests();
registerStickyPistonTests();
registerRedstoneBlockTests();
registerRedstoneOreTests();
registerRedstoneTorchTests();
registerTargetBlockTests();
registerWeightedPressurePlateTests();
registerBeaconTests();
