// mob_behavior 行为包入口：注册生物行为类 GameTest。
// 测试按主角生物的 Cubium 实体分类（src/common/entity/entities）拆分到 src/tests/ 子目录，
// 未来为每个生物加行为测试时，放入对应分类目录即可。

// 必须最先 import（副作用执行）：GameTest RegistrationBuilder 跨服务端兼容垫片。
// Cubium 在官方 RegistrationBuilder 之上扩展了 skyAccess/setupTicks 链式方法（基岩 BDS 无此方法，
// 调用抛 TypeError 致整个行为包加载失败）。垫片在基岩侧用 Proxy 把这些专有方法降级为 no-op，
// Cubium 侧因 register 为 read-only 赋值失败而静默保留原实现。详见 gametest-shim.ts。
import "./gametest-shim.js";

import { registerZombieTests } from "./tests/monster/undead/ZombieTests.js";
import { registerSkeletonTests } from "./tests/monster/undead/SkeletonTests.js";
import { registerIronGolemTests } from "./tests/passive/golem/IronGolemTests.js";
import { registerSnowGolemTests } from "./tests/passive/golem/SnowGolemTests.js";
import { registerZoglinTests } from "./tests/monster/nether/ZoglinTests.js";
import { registerMagmaCubeTests } from "./tests/monster/nether/MagmaCubeTests.js";
import { registerZombifiedPiglinTests } from "./tests/monster/nether/ZombifiedPiglinTests.js";
import { registerBlazeTests } from "./tests/monster/nether/BlazeTests.js";
import { registerGuardianTests } from "./tests/monster/ocean/GuardianTests.js";
import { registerElderGuardianTests } from "./tests/monster/ocean/ElderGuardianTests.js";
import { registerEndermanTests } from "./tests/monster/end/EndermanTests.js";
import { registerShulkerTests } from "./tests/monster/end/ShulkerTests.js";
import { registerWitherSkeletonTests } from "./tests/monster/undead/WitherSkeletonTests.js";
import { registerHuskTests } from "./tests/monster/undead/HuskTests.js";
import { registerDrownedTests } from "./tests/monster/undead/DrownedTests.js";
import { registerStrayTests } from "./tests/monster/undead/StrayTests.js";
import { registerBoggedTests } from "./tests/monster/undead/BoggedTests.js";
import { registerPhantomTests } from "./tests/monster/basic/PhantomTests.js";
import { registerCreeperTests } from "./tests/monster/basic/CreeperTests.js";
import { registerSlimeTests } from "./tests/monster/basic/SlimeTests.js";
import { registerSpiderTests } from "./tests/monster/arthropod/SpiderTests.js";
import { registerCaveSpiderTests } from "./tests/monster/arthropod/CaveSpiderTests.js";
import { registerEndermiteTests } from "./tests/monster/arthropod/EndermiteTests.js";
import { registerSilverfishTests } from "./tests/monster/arthropod/SilverfishTests.js";
import { registerWitchTests } from "./tests/monster/illager/WitchTests.js";
import { registerRavagerTests } from "./tests/monster/illager/RavagerTests.js";
import { registerVexTests } from "./tests/monster/illager/VexTests.js";
import { registerEvokerTests } from "./tests/monster/illager/EvokerTests.js";
import { registerIllusionerTests } from "./tests/monster/illager/IllusionerTests.js";
import { registerPillagerTests } from "./tests/monster/illager/PillagerTests.js";
import { registerVindicatorTests } from "./tests/monster/illager/VindicatorTests.js";
import { registerPigTests } from "./tests/passive/basic/PigTests.js";
import { registerCowTests } from "./tests/passive/basic/CowTests.js";
import { registerSheepTests } from "./tests/passive/basic/SheepTests.js";
import { registerChickenTests } from "./tests/passive/basic/ChickenTests.js";
import { registerRabbitTests } from "./tests/passive/basic/RabbitTests.js";
import { registerMooshroomTests } from "./tests/passive/basic/MooshroomTests.js";
import { registerBatTests } from "./tests/passive/ambient/BatTests.js";
import { registerPolarBearTests } from "./tests/passive/special/PolarBearTests.js";
import { registerFoxTests } from "./tests/passive/special/FoxTests.js";
import { registerBeeTests } from "./tests/passive/special/BeeTests.js";
import { registerStriderTests } from "./tests/passive/special/StriderTests.js";
import { registerWolfTests } from "./tests/passive/tamable/WolfTests.js";
import { registerCatTests } from "./tests/passive/tamable/CatTests.js";
import { registerOcelotTests } from "./tests/passive/tamable/OcelotTests.js";
import { registerLlamaTests } from "./tests/passive/horse/LlamaTests.js";
import { registerSkeletonHorseTests } from "./tests/passive/horse/SkeletonHorseTests.js";
import { registerBreezeTests } from "./tests/monster/breeze/BreezeTests.js";
import { registerSquidTests } from "./tests/passive/water/SquidTests.js";
import { registerGlowSquidTests } from "./tests/passive/water/GlowSquidTests.js";
import { registerAxolotlTests } from "./tests/passive/water/AxolotlTests.js";
import { registerPufferfishTests } from "./tests/passive/fish/PufferfishTests.js";

registerZombieTests();
registerSkeletonTests();
registerIronGolemTests();
registerSnowGolemTests();
registerZoglinTests();
registerMagmaCubeTests();
registerZombifiedPiglinTests();
registerBlazeTests();
registerGuardianTests();
registerElderGuardianTests();
registerEndermanTests();
registerShulkerTests();
registerWitherSkeletonTests();
registerHuskTests();
registerDrownedTests();
registerStrayTests();
registerBoggedTests();
registerPhantomTests();
registerCreeperTests();
registerSlimeTests();
registerSpiderTests();
registerCaveSpiderTests();
registerEndermiteTests();
registerSilverfishTests();
registerWitchTests();
registerRavagerTests();
registerVexTests();
registerEvokerTests();
registerIllusionerTests();
registerPillagerTests();
registerVindicatorTests();
registerPigTests();
registerCowTests();
registerSheepTests();
registerChickenTests();
registerRabbitTests();
registerMooshroomTests();
registerBatTests();
registerPolarBearTests();
registerFoxTests();
registerBeeTests();
registerStriderTests();
registerWolfTests();
registerCatTests();
registerOcelotTests();
registerLlamaTests();
registerSkeletonHorseTests();
registerBreezeTests();
registerSquidTests();
registerGlowSquidTests();
registerAxolotlTests();
registerPufferfishTests();
