// mob_behavior 行为包入口：注册生物行为类 GameTest。
// 测试按主角生物的 Cubium 实体分类（src/common/entity/entities）拆分到 src/tests/ 子目录，
// 未来为每个生物加行为测试时，放入对应分类目录即可。

// 必须最先 import（副作用执行）：GameTest RegistrationBuilder 跨服务端兼容垫片。
// Cubium 在官方 RegistrationBuilder 之上扩展了 skyAccess/setupTicks 链式方法（基岩 BDS 无此方法，
// 调用抛 TypeError 致整个行为包加载失败）。垫片在基岩侧用 Proxy 把这些专有方法降级为 no-op，
// Cubium 侧因 register 为 read-only 赋值失败而静默保留原实现。详见 gametest-shim.ts。
import "./gametest-shim.js";

import { registerZombieTests } from "./tests/monster/undead/ZombieTests.js";
import { registerWitherTests } from "./tests/boss/WitherTests.js";
import { registerEffectImmunityTests } from "./tests/monster/undead/EffectImmunityTests.js";
import { registerMeleeEnchantDamageTests } from "./tests/combat/MeleeEnchantDamageTests.js";
import { registerArmorDamageReductionTests } from "./tests/combat/ArmorDamageReductionTests.js";
import { registerFireAspectEnchantTests } from "./tests/combat/FireAspectEnchantTests.js";
import { registerFireProtectionBurningTimeTests } from "./tests/combat/FireProtectionBurningTimeTests.js";
import { registerThornsEnchantTests } from "./tests/combat/ThornsEnchantTests.js";
import { registerBaneOfArthropodsSlownessTests } from "./tests/combat/BaneOfArthropodsSlownessTests.js";
import { registerBlastProtectionKnockbackTests } from "./tests/combat/BlastProtectionKnockbackTests.js";
import { registerProjectileDeflectTests } from "./tests/combat/ProjectileDeflectTests.js";
import { registerBowArrowDamageTests } from "./tests/combat/BowArrowDamageTests.js";
import { registerCrossbowTests } from "./tests/combat/CrossbowTests.js";
import { registerSpectralArrowTests } from "./tests/combat/SpectralArrowTests.js";
import { registerFireImmunityTests } from "./tests/combat/FireImmunityTests.js";
import { registerFallDamageTests } from "./tests/combat/FallDamageTests.js";
import { registerFeatherFallingTests } from "./tests/combat/FeatherFallingTests.js";
import { registerResistanceEffectTests } from "./tests/combat/ResistanceEffectTests.js";
import { registerWitherEffectTests } from "./tests/combat/WitherEffectTests.js";
import { registerShieldDisableTests } from "./tests/combat/ShieldDisableTests.js";
import { registerShieldDurabilityTests } from "./tests/combat/ShieldDurabilityTests.js";
import { registerCooldownScalingTests } from "./tests/combat/CooldownScalingTests.js";
import { registerSweepAttackTests } from "./tests/combat/SweepAttackTests.js";
import { registerKnockbackTests } from "./tests/combat/KnockbackTests.js";
import { registerBreachEnchantmentTests } from "./tests/combat/BreachEnchantmentTests.js";
import { registerWindBurstEnchantmentTests } from "./tests/combat/WindBurstEnchantmentTests.js";
import { registerWardenTests } from "./tests/boss/WardenTests.js";
import { registerDragonFireballTests } from "./tests/boss/DragonFireballTests.js";
import { registerSkeletonTests } from "./tests/monster/undead/SkeletonTests.js";
import { registerIronGolemTests } from "./tests/passive/golem/IronGolemTests.js";
import { registerSnowGolemTests } from "./tests/passive/golem/SnowGolemTests.js";
import { registerZoglinTests } from "./tests/monster/nether/ZoglinTests.js";
import { registerHoglinTests } from "./tests/monster/nether/HoglinTests.js";
import { registerPiglinBruteTests } from "./tests/monster/nether/PiglinBruteTests.js";
import { registerMagmaCubeTests } from "./tests/monster/nether/MagmaCubeTests.js";
import { registerZombifiedPiglinTests } from "./tests/monster/nether/ZombifiedPiglinTests.js";
import { registerPiglinTests } from "./tests/monster/nether/PiglinTests.js";
import { registerBlazeTests } from "./tests/monster/nether/BlazeTests.js";
import { registerGhastTests } from "./tests/monster/nether/GhastTests.js";
import { registerGuardianTests } from "./tests/monster/ocean/GuardianTests.js";
import { registerElderGuardianTests } from "./tests/monster/ocean/ElderGuardianTests.js";
import { registerEndermanTests } from "./tests/monster/end/EndermanTests.js";
import { registerShulkerTests } from "./tests/monster/end/ShulkerTests.js";
import { registerWitherSkeletonTests } from "./tests/monster/undead/WitherSkeletonTests.js";
import { registerHuskTests } from "./tests/monster/undead/HuskTests.js";
import { registerDrownedTests } from "./tests/monster/undead/DrownedTests.js";
import { registerStrayTests } from "./tests/monster/undead/StrayTests.js";
import { registerBoggedTests } from "./tests/monster/undead/BoggedTests.js";
import { registerPhantomTests } from "./tests/monster/basic/PhantomTests.js";
import { registerCreeperTests } from "./tests/monster/basic/CreeperTests.js";
import { registerSlimeTests } from "./tests/monster/basic/SlimeTests.js";
import { registerSpiderTests } from "./tests/monster/arthropod/SpiderTests.js";
import { registerCaveSpiderTests } from "./tests/monster/arthropod/CaveSpiderTests.js";
import { registerEndermiteTests } from "./tests/monster/arthropod/EndermiteTests.js";
import { registerSilverfishTests } from "./tests/monster/arthropod/SilverfishTests.js";
import { registerWitchTests } from "./tests/monster/illager/WitchTests.js";
import { registerRavagerTests } from "./tests/monster/illager/RavagerTests.js";
import { registerVexTests } from "./tests/monster/illager/VexTests.js";
import { registerEvokerTests } from "./tests/monster/illager/EvokerTests.js";
import { registerIllusionerTests } from "./tests/monster/illager/IllusionerTests.js";
import { registerPillagerTests } from "./tests/monster/illager/PillagerTests.js";
import { registerVindicatorTests } from "./tests/monster/illager/VindicatorTests.js";
import { registerPigTests } from "./tests/passive/basic/PigTests.js";
import { registerCowTests } from "./tests/passive/basic/CowTests.js";
import { registerCowBreedTests } from "./tests/passive/basic/CowBreedTests.js";
import { registerBabyCowTests } from "./tests/passive/basic/BabyCowTests.js";
import { registerSheepTests } from "./tests/passive/basic/SheepTests.js";
import { registerChickenTests } from "./tests/passive/basic/ChickenTests.js";
import { registerRabbitTests } from "./tests/passive/basic/RabbitTests.js";
import { registerMooshroomTests } from "./tests/passive/basic/MooshroomTests.js";
import { registerBatTests } from "./tests/passive/ambient/BatTests.js";
import { registerPolarBearTests } from "./tests/passive/special/PolarBearTests.js";
import { registerFoxTests } from "./tests/passive/special/FoxTests.js";
import { registerSnifferTests } from "./tests/passive/special/SnifferTests.js";
import { registerPandaTests } from "./tests/passive/special/PandaTests.js";
import { registerTurtleTests } from "./tests/passive/special/TurtleTests.js";
import { registerBeeTests } from "./tests/passive/special/BeeTests.js";
import { registerStriderTests } from "./tests/passive/special/StriderTests.js";
import { registerWolfTests } from "./tests/passive/tamable/WolfTests.js";
import { registerCatTests } from "./tests/passive/tamable/CatTests.js";
import { registerOcelotTests } from "./tests/passive/tamable/OcelotTests.js";
import { registerParrotTests } from "./tests/passive/tamable/ParrotTests.js";
import { registerLlamaTests } from "./tests/passive/horse/LlamaTests.js";
import { registerTraderLlamaTests } from "./tests/passive/horse/TraderLlamaTests.js";
import { registerHorseTests } from "./tests/passive/horse/HorseTests.js";
import { registerDonkeyTests } from "./tests/passive/horse/DonkeyTests.js";
import { registerLlamaChestTests } from "./tests/passive/horse/LlamaChestTests.js";
import { registerSkeletonHorseTests } from "./tests/passive/horse/SkeletonHorseTests.js";
import { registerZombieHorseTests } from "./tests/passive/horse/ZombieHorseTests.js";
import { registerBreezeTests } from "./tests/monster/breeze/BreezeTests.js";
import { registerSquidTests } from "./tests/passive/water/SquidTests.js";
import { registerGlowSquidTests } from "./tests/passive/water/GlowSquidTests.js";
import { registerAxolotlTests } from "./tests/passive/water/AxolotlTests.js";
import { registerDolphinTests } from "./tests/passive/water/DolphinTests.js";
import { registerPufferfishTests } from "./tests/passive/fish/PufferfishTests.js";
import { registerCodTests } from "./tests/passive/fish/CodTests.js";
import { registerFishBucketPickupTests } from "./tests/passive/fish/FishBucketPickupTests.js";
import { registerFishBucketReleaseTests } from "./tests/passive/fish/FishBucketReleaseTests.js";
import { registerPowderSnowBucketReleaseTests } from "./tests/passive/special/PowderSnowBucketReleaseTests.js";
import { registerBucketItemTests } from "./tests/passive/special/BucketItemTests.js";
import { registerFlintAndSteelDurabilityTests } from "./tests/passive/special/FlintAndSteelDurabilityTests.js";
import { registerHoeDurabilityTests } from "./tests/passive/special/HoeDurabilityTests.js";
import { registerShearsDurabilityTests } from "./tests/passive/special/ShearsDurabilityTests.js";
import { registerSaddleConsumptionTests } from "./tests/passive/special/SaddleConsumptionTests.js";
import { registerNameTagConsumptionTests } from "./tests/passive/special/NameTagConsumptionTests.js";
import { registerBowDurabilityTests } from "./tests/passive/special/BowDurabilityTests.js";
import { registerTridentConsumptionTests } from "./tests/passive/special/TridentConsumptionTests.js";
import { registerFoodContainerConsumptionTests } from "./tests/passive/special/FoodContainerConsumptionTests.js";
import { registerMilkBucketConsumptionTests } from "./tests/passive/special/MilkBucketConsumptionTests.js";
import { registerHoneyBottleConsumptionTests } from "./tests/passive/special/HoneyBottleConsumptionTests.js";
import { registerPotionConsumptionTests } from "./tests/passive/special/PotionConsumptionTests.js";
import { registerThrowableItemTests } from "./tests/passive/special/ThrowableItemTests.js";
import { registerFishingRodTests } from "./tests/passive/special/FishingRodTests.js";
import { registerNautilusTests } from "./tests/passive/nautilus/NautilusTests.js";
import { registerZombieNautilusTests } from "./tests/passive/nautilus/ZombieNautilusTests.js";
import { registerMobSpawnerTests } from "./tests/spawn/spawner/MobSpawnerTests.js";
import { registerDespawnTests } from "./tests/spawn/despawn/DespawnTests.js";
import { registerNaturalSpawnTests } from "./tests/spawn/natural/NaturalSpawnTests.js";
import { registerZombieReinforcementTests } from "./tests/spawn/reinforcement/ZombieReinforcementTests.js";
import { registerMobDeathLootTests } from "./tests/spawn/loot/MobDeathLootTests.js";
import { registerMobDeathXpTests } from "./tests/spawn/loot/MobDeathXpTests.js";
import { registerMobEquipmentDropTests } from "./tests/spawn/loot/MobEquipmentDropTests.js";
import { registerPlayerDeathLootTests } from "./tests/spawn/loot/PlayerDeathLootTests.js";
import { registerZombieVillagerTests } from "./tests/monster/undead/ZombieVillagerTests.js";
import { registerGoldenAppleConsumptionTests } from "./tests/monster/undead/GoldenAppleConsumptionTests.js";
import { registerGoldenAppleSelfConsumptionTests } from "./tests/monster/undead/GoldenAppleSelfConsumptionTests.js";
import { registerZombieBreakDoorTests } from "./tests/monster/undead/ZombieBreakDoorTests.js";
import { registerVillagerTests } from "./tests/passive/villager/VillagerTests.js";
import { registerVillagerBreedTests } from "./tests/passive/villager/VillagerBreedTests.js";
import { registerWanderingTraderTests } from "./tests/passive/villager/WanderingTraderTests.js";

registerZombieTests();
registerSkeletonTests();
registerIronGolemTests();
registerSnowGolemTests();
registerZoglinTests();
registerHoglinTests();
registerPiglinBruteTests();
registerMagmaCubeTests();
registerZombifiedPiglinTests();
registerPiglinTests();
registerBlazeTests();
registerGhastTests();
registerGuardianTests();
registerElderGuardianTests();
registerEndermanTests();
registerShulkerTests();
registerWitherSkeletonTests();
registerHuskTests();
registerDrownedTests();
registerStrayTests();
registerBoggedTests();
registerPhantomTests();
registerCreeperTests();
registerSlimeTests();
registerSpiderTests();
registerCaveSpiderTests();
registerEndermiteTests();
registerSilverfishTests();
registerWitchTests();
registerRavagerTests();
registerVexTests();
registerEvokerTests();
registerIllusionerTests();
registerPillagerTests();
registerVindicatorTests();
registerPigTests();
registerCowTests();
registerCowBreedTests();
registerBabyCowTests();
registerSheepTests();
registerChickenTests();
registerRabbitTests();
registerMooshroomTests();
registerBatTests();
registerPolarBearTests();
registerFoxTests();
registerSnifferTests();
registerPandaTests();
registerTurtleTests();
registerBeeTests();
registerStriderTests();
registerWolfTests();
registerCatTests();
registerOcelotTests();
registerParrotTests();
registerLlamaTests();
registerTraderLlamaTests();
registerHorseTests();
registerDonkeyTests();
registerLlamaChestTests();
registerSkeletonHorseTests();
registerZombieHorseTests();
registerBreezeTests();
registerSquidTests();
registerGlowSquidTests();
registerAxolotlTests();
registerDolphinTests();
registerPufferfishTests();
registerCodTests();
registerFishBucketPickupTests();
registerFishBucketReleaseTests();
registerPowderSnowBucketReleaseTests();
registerBucketItemTests();
registerFlintAndSteelDurabilityTests();
registerHoeDurabilityTests();
registerShearsDurabilityTests();
registerSaddleConsumptionTests();
registerNameTagConsumptionTests();
registerBowDurabilityTests();
registerBowArrowDamageTests();
registerCrossbowTests();
registerSpectralArrowTests();
registerTridentConsumptionTests();
registerFoodContainerConsumptionTests();
registerMilkBucketConsumptionTests();
registerHoneyBottleConsumptionTests();
registerPotionConsumptionTests();
registerThrowableItemTests();
registerFishingRodTests();
registerNautilusTests();
registerZombieNautilusTests();
registerMobSpawnerTests();
registerDespawnTests();
registerNaturalSpawnTests();
registerZombieReinforcementTests();
registerMobDeathLootTests();
registerMobDeathXpTests();
registerMobEquipmentDropTests();
registerPlayerDeathLootTests();
registerZombieVillagerTests();
registerGoldenAppleConsumptionTests();
registerGoldenAppleSelfConsumptionTests();
registerZombieBreakDoorTests();
registerVillagerTests();
registerVillagerBreedTests();
registerWanderingTraderTests();
registerWitherTests();
registerWardenTests();
registerDragonFireballTests();
registerEffectImmunityTests();
registerMeleeEnchantDamageTests();
registerArmorDamageReductionTests();
registerFireAspectEnchantTests();
registerFireProtectionBurningTimeTests();
registerThornsEnchantTests();
registerBaneOfArthropodsSlownessTests();
registerBlastProtectionKnockbackTests();
registerProjectileDeflectTests();
registerFireImmunityTests();
registerFallDamageTests();
registerFeatherFallingTests();
registerResistanceEffectTests();
registerWitherEffectTests();
registerShieldDisableTests();
registerShieldDurabilityTests();
registerCooldownScalingTests();
registerSweepAttackTests();
registerKnockbackTests();
registerBreachEnchantmentTests();
registerWindBurstEnchantmentTests();
